# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8.0

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix do deps.get, deps.compile
      - run: mix dialyzer
      - run: mix test
